name: shopping_store
version: 1.0.0+1
description: Shooping Store.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter_spinkit: ^5.1.0
  animated_splash_screen: ^1.1.0
  cached_network_image: ^3.1.0+1
  auto_size_text: 3.0.0
  ionicons: 0.1.2
  font_awesome_flutter: 9.2.0
  flutter_switch: 0.3.2
  modal_progress_hud_nsn: 0.1.0-nullsafety-1
  gender_picker: 1.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

